TTMS/urls.py
#coding=utf-8
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import (
    password_reset, password_reset_done, password_reset_confirm,
    password_reset_complete, password_change, password_change_done)
from django.contrib import admin
from TTMS.site import site as admin_site
from member.sites import site as member_site
from management.sites import site as management_site


urlpatterns = patterns(
    '',
    #=================================== ADMIN =================================
    # url(r'^admin/$', admin.site.index, name='index'),
    # url(r'^admin/login/$', admin.site.login, name='login'),
    # url(r'^admin/logout/$', admin.site.logout, name='logout'),
    # url(r'^admin/password_change/$', admin.site.password_change, name='password_change'),
    # url(r'^admin/password_change/done/$', admin.site.password_change_done, name='password_change_done'),
    # url(r'^admin/jsi18n/$', admin.site.i18n_javascript, name='jsi18n'),
    # url(r'^admin/r/(?P<content_type_id>\d+)/(?P<object_id>.+)/$', contenttype_views.shortcut, name='view_on_site'),

    url(r'^', include(member_site.urls)),
    url(r'^staff/', include(management_site.urls)),
    url(r'^admin/', include(admin.site.urls)),

    # #=================================== BANK ===============================
    # url(r'^member/bank_register/$', 'member.views.bank_register'),
    # url(r'^member/bank_login/$', 'member.views.bank_login'),
    # url(r'^member/create_bank/$', 'member.views.create_bank'),
    # # url(r'^member/createbank/$', BankCreateView.as_view(), name='createbank'),
    # #=================================== ENTERPRISE ===============================
    # url(r'^member/enterprise_register/$', 'member.views.enterprise_register'),
    # url(r'^member/enterprise_login/$', 'member.views.enterprise_login'),

    # 登陆后根据用户身份统一跳转
    url(r'^login_redirect/$', 'TTMS.auth.login_redirect'),

    #=================================== MANAGEMENT ===============================
    url(r'^management/login/$', 'management.auth.login'),
    url(r'^management/logout/$', 'management.auth.logout'),
    url(r'^management/logout_then_login/$', 'management.auth.logout_then_login'),
    url(r'^management/redirect_to_login/$', 'management.auth.redirect_to_login'),
    # password
    url(r'^management/password_reset/$', password_reset, {'post_reset_redirect': '/management/password_reset_done'}),
    url(r'^management/password_reset_done/$', password_reset_done),
    url(r'^management/password_reset_confirm/$', password_reset_confirm),
    url(r'^management/password_reset_complete/$', password_reset_complete),
    # password_change
    url(r'^management/password_change/$', password_change, {'post_change_redirect': '/management/password_change_done'}),
    url(r'^management/password_change_done/$', password_change_done, {'template_name': 'registration/password_change_done.html'}),
    # 工作人员dashboard主界面
    url(r'^management/main/$', 'management.views.main_view'),

    #=================================== MEMBER ===============================
    url(r'^member/login/', 'member.auth.login'),
    url(r'^member/logout/', 'member.auth.logout'),
    url(r'^member/logout_then_login/', 'member.auth.logout_then_login'),
    url(r'^member/redirect_to_login/', 'member.auth.redirect_to_login'),
    # password_reset
    # todo reset 除了邮箱还要加上手机
    url(r'^member/password_reset/$', password_reset, {'template_name': 'member/registration/password_reset_form.html', 'post_reset_redirect': '/member/password_reset_done'}),
    url(r'^member/password_reset_done/$', password_reset_done, {'template_name': 'member/registration/password_reset_done.html'}),
    url(r'^member/password_reset_confirm/$', password_reset_confirm, {'template_name': 'member/registration/password_reset_confirm.html'}),
    url(r'^member/password_reset_complete/$', password_reset_complete, {'template_name': 'member/registration/password_reset_complete.html'}),

    # password_change
    # moved into member/sites.py
    # url(r'^member/password_change/$', password_change, {'post_change_redirect': '/member/password_change_done'}),
    # url(r'^member/password_change_done/$', password_change_done, {'template_name': 'registration/password_change_done.html'}),

    # 主界面
    url(r'^member/main/$', 'member.views.member_main'),

    # 附件
    url(r'^template/thumbnail/(?P<filename>.*)$', 'utils.views.get_template_thumbnail'),
    url(r'^template/(?P<filename>.*)$', 'utils.views.get_template_document'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': './media', 'show_indexes': True}),
    url(r'^bank/(?P<bank_id>.*)/attachment/thumbnail/(?P<filename>.*)$', 'member.views.get_bank_attachment_thumbnail'),
    url(r'^bank/(?P<bank_id>.*)/attachment/(?P<filename>.*)$', 'member.views.get_bank_attachment'),
    url(r'^enterprise/(?P<enterprise_id>.*)/attachment/thumbnail/(?P<filename>.*)$', 'member.views.get_enterprise_attachment_thumbnail'),
    url(r'^enterprise/(?P<enterprise_id>.*)/attachment/(?P<filename>.*)$', 'member.views.get_enterprise_attachment'),
    url(r'^transactionorder/(?P<transaction_id>.*)/operation/(?P<operation_id>.*)/attachment/thumbnail/(?P<filename>.*)$', 'transaction.views.get_operation_attachment_thumbnail'),
    url(r'^transactionorder/(?P<transaction_id>.*)/operation/(?P<operation_id>.*)/attachment/(?P<filename>.*)$', 'transaction.views.get_operation_attachment'),

    # 手机邮件验证码
    url(r'^send_sms_verify.php', 'utils.views.send_sms_verify'),
    url(r'^utils/send_sms_verify', 'utils.views.send_sms_verify'),
    url(r'^utils/send_email_verify/$', 'utils.views.send_email_verify'),

)

member/models.py
#coding=utf-8

from django.db import models
from management.models import Province
from django.contrib.auth.models import User, UserManager
from django.db.models.signals import *
from django.core import validators
from utils.constants import MEMBER_USER_TYPE
from management.models import Staff
from TTMS.settings import MEDIA_URL, MEDIA_ROOT, BASE_URL
from django.utils.http import urlquote
from PIL import Image
import os
from utils.func import make_thumb
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _


module = __name__[:__name__.find('.')]

#=====================================================注册邀请码======================================================

CODE_PENDING = 'PENDING'
CODE_ACTIVATED = 'Activated'
CODE_USED = 'Used'
CODE_INACTIVED = 'Inactived'
CODE_STATUS = (
    (CODE_PENDING, u'待审核'),
    (CODE_ACTIVATED, u'未使用'),
    (CODE_USED, u'已使用'),
    (CODE_INACTIVED, u'已作废'),
)

BANK_MEMBER = 'Bank'
ENTERPRISE_MEMBER = 'Enterprise'
MEMBER_TYPE = (
    (BANK_MEMBER, u'银行会员'),
    (ENTERPRISE_MEMBER, u'企业会员'),
)


class RegisterInvitationCode(models.Model):
    code = models.CharField(unique=True, max_length=30, blank=False, null=False, verbose_name=u'邀请码')
    member_name = models.CharField(max_length=50, blank=False, null=False, verbose_name=u'会员名称')
    member_type = models.CharField(max_length=20, choices=MEMBER_TYPE, verbose_name=u'会员类型')
    contactor_name = models.CharField(max_length=20, blank=False, null=False, verbose_name=u'主联络人姓名')
    contactor_email = models.EmailField(max_length=50, blank=False, null=False, verbose_name=u'主联络人邮箱')
    referee_member_type = models.CharField(max_length=20, blank=True, null=True, choices=MEMBER_TYPE, verbose_name=u'推荐会员类型')
    referee_member_id = models.BigIntegerField(blank=True, null=True, verbose_name=u'推荐会员编号')
    status = models.CharField(max_length=10, choices=CODE_STATUS, default=CODE_ACTIVATED, verbose_name=u'邀请码状态')
    market_manager = models.ForeignKey(Staff, blank=True, null=True, verbose_name=u'市场经理')
    used_date = models.DateTimeField(blank=True, null=True, editable=True, verbose_name=u'使用时间')
    create_date = models.DateTimeField(auto_now_add=True, editable=True, verbose_name=u'创建时间')

    class Meta:
        verbose_name = u'注册邀请码'
        verbose_name_plural = u'注册邀请码'

    def __unicode__(self):
        return u'[邀请码]%s' % self.code

    def get_referee(self):
        if self.referee_member_type == BANK_MEMBER:
            return Bank.objects.get(id=self.referee_member_id)
        elif self.referee_member_type == ENTERPRISE_MEMBER:
            return Enterprise.objects.get(id=self.referee_member_id)
        else:
            return None

    def get_referee_name(self):
        if self.referee_member_type == BANK_MEMBER:
            referee = Bank.objects.get(id=self.referee_member_id)
            return u'[银行会员]%s' % referee.name
        elif self.referee_member_type == ENTERPRISE_MEMBER:
            referee = Enterprise.objects.get(id=self.referee_member_id)
            return u'[企业会员]%s' % referee.name
        else:
            return None

    @property
    def url(self):
        return '%s/member/%s/register?code=%s' % (BASE_URL, self.member_type.lower(), self.code)


#=====================================================会员单位======================================================

MEMBER_ENABLED = 'Enabled'
MEMBER_PENDING = 'Pending'
MEMBER_DISABLED = 'Disabled'
MEMBER_EXPIRED = 'Expired'

MEMBER_STATUS = (
    (MEMBER_ENABLED, u'正常'),
    (MEMBER_PENDING, u'待审核'),
    (MEMBER_DISABLED, u'禁用'),
    (MEMBER_EXPIRED, u'过期'),
)

MEMBER_LEVEL_1 = '1'
MEMBER_LEVEL_2 = '2'
MEMBER_LEVEL_3 = '3'
MEMBER_LEVEL_4 = '4'
MEMBER_LEVEL_5 = '5'
MEMBER_LEVEL_6 = '6'
MEMBER_LEVEL = (
    (MEMBER_LEVEL_1, u'一星会员'),
    (MEMBER_LEVEL_2, u'二星会员'),
    (MEMBER_LEVEL_3, u'三星会员'),
    (MEMBER_LEVEL_4, u'四星会员'),
    (MEMBER_LEVEL_5, u'五星会员'),
    (MEMBER_LEVEL_6, u'六星会员'),
)


class Enterprise(models.Model):
    name = models.CharField(unique=True, max_length=50, blank=False, null=False, verbose_name=u'企业名称')
    province = models.ForeignKey(Province, verbose_name=u'省份')
    city = models.CharField(max_length=20, blank=False, null=False, verbose_name=u'城市')
    address = models.CharField(max_length=100, blank=False, null=False, verbose_name=u'地址')
    zipcode = models.IntegerField(blank=False, null=False, verbose_name=u'邮编')
    fax_number = models.IntegerField(blank=False, null=False, verbose_name=u'传真号')
    # licence = models.ImageField(upload_to='.', blank=True, null=True, verbose_name=u'营业执照')
    # organization_code = models.ImageField(upload_to='.', blank=True, null=True, verbose_name=u'组织代码证')
    # tax_registration = models.ImageField(upload_to='.', blank=True, null=True, verbose_name=u'税务登记证')
    level = models.CharField(max_length=20, choices=MEMBER_LEVEL, default=MEMBER_LEVEL_1, verbose_name=u'会员星级')
    # contactor = models.ForeignKey(EnterpriseContactor, verbose_name=u'主联络人')
    # operator = models.ForeignKey(EnterpriseOperator, verbose_name=u'执行人')
    status = models.CharField(max_length=20, choices=MEMBER_STATUS, default=MEMBER_PENDING, verbose_name=u'会员状态')
    invite_code = models.OneToOneField(RegisterInvitationCode, blank=True, null=True, verbose_name=u'邀请码')
    referee_manager = models.ForeignKey(Staff, blank=True, null=True, verbose_name=u'推荐市场经理', related_name='enterprise_referee_manager')
    service_manager = models.ForeignKey(Staff, blank=True, null=True, verbose_name=u'服务市场经理', related_name='enterprise_service_manager')
    reference_count = models.IntegerField(blank=False, null=False, default=0, verbose_name=u'成功推荐注册数')
    create_date = models.DateTimeField(auto_now_add=True, editable=True, verbose_name=u'注册时间')
    modify_date = models.DateTimeField(auto_now_add=True, auto_now=True, editable=True, verbose_name=u'最后修改时间')

    class Meta:
        verbose_name = u'企业会员'
        verbose_name_plural = u'企业会员'
        permissions = (("register_enterprise", u"注册企业会员"),)

    def __unicode__(self):
        return self.name

    def confirm_name_link(self):
        return u'<a href="/staff/member/enterprise/%s/confirm">%s</a>' % (self.id, self.name)

    confirm_name_link.allow_tags = True
    confirm_name_link.short_description = u'企业名称'

    def confirm_button_link(self):
        return u'<a class="button" href="/staff/member/enterprise/%s/confirm">进行审核</a>' % self.id

    confirm_button_link.allow_tags = True
    confirm_button_link.short_description = u'注册审核'


class EnterpriseContactor(models.Model):
    user = models.OneToOneField(User, blank=True, null=True, verbose_name=u'登陆账号')
    enterprise = models.OneToOneField(Enterprise, blank=False, null=False, verbose_name=u'所属企业', related_name='contactor')
    username = models.CharField(unique=True, max_length=30, blank=False, null=False, verbose_name=u'用户名', help_text=u'长度小于30，只限字母、数字及符号@.+-_')
    #groupname = models.CharField(max_length=20, blank=True, null=True, choices=MEMBER_USER_TYPE, verbose_name=u'角色名称', help_text=u'角色名称')
    # password = models.CharField(max_length=20, blank=False, null=False, verbose_name=u'密码')
    name = models.CharField(max_length=50, blank=False, null=False, verbose_name=u'姓名')
    identity_card = models.CharField(max_length=20, blank=False, null=False, verbose_name=u'身份证')
    mobile_number = models.BigIntegerField(max_length=11, blank=False, null=False, verbose_name=u'手机号')
    telephone = models.BigIntegerField(max_length=11, blank=True, null=True, verbose_name=u'固定电话')
    email = models.EmailField(max_length=50, blank=False, null=False, verbose_name=u'电子邮箱')
    # fax_number = models.BigIntegerField(max_length=11, blank=True, null=True, verbose_name=u'传真号')
    position = models.CharField(max_length=20, blank=True, null=True, verbose_name=u'职位')
    pwd_question = models.CharField(max_length=100, blank=False, null=False, verbose_name=u'密码提示问题')
    pwd_answer = models.CharField(max_length=50, blank=False, null=False, verbose_name=u'密码提示问题答案')
    last_login = models.DateTimeField(blank=True, null=True, editable=False, verbose_name=u'上次登录时间')
    create_date = models.DateTimeField(auto_now_add=True, editable=True, verbose_name=u'创建时间')
    modify_date = models.DateTimeField(auto_now_add=True, auto_now=True, editable=True, verbose_name=u'最后修改时间')

    class Meta:
        verbose_name = u'企业会员主联络人'
        verbose_name_plural = u'企业会员主联络人'
        unique_together = (('user', 'enterprise'),)

    def __unicode__(self):
        return u'[%s主联络人]%s' % (self.enterprise.name, self.name)

    @property
    def groupname(self):
        if self.user.groups.count() > 0:
            return self.user.groups.all()[0].name
        else:
            return None

    @property
    def grouptype(self):
        if self.user.groups.count() > 0:
            return self.user.groups.all()[0].id
        else:
            return None

    @property
    def is_contactor(self):
        return True

    @property
    def member_type(self):
        return 'enterprise'

    @property
    def contactor_id(self):
        return self.id

    @property
    def member_id(self):
        return self.enterprise_id

        # @property
        # def username(self):
        #     return self.user.username


class EnterpriseOperator(models.Model):
    user = models.OneToOneField(User, blank=False, null=False, verbose_name=u'登陆账号')
    enterprise = models.OneToOneField(Enterprise, blank=False, null=False, verbose_name=u'所属企业', related_name='operator')  # 企业只能有一个执行人 one to one
    username = models.CharField(unique=True, max_length=30, blank=False, null=False, verbose_name=u'用户名', help_text=u'长度小于30，只限字母、数字及符号@.+-_')

management/views.py
#coding=utf-8
from django.shortcuts import get_object_or_404, render_to_response, render, redirect
from django.http import HttpResponse
from django.template.response import TemplateResponse
from django.forms.models import modelformset_factory, inlineformset_factory
from django.forms import ModelForm
from django.views.generic import CreateView, UpdateView
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.template import RequestContext
from django.core.exceptions import NON_FIELD_ERRORS
from django.http import HttpResponse, HttpResponseRedirect

from management.models import Staff
from management.auth import login, logout, logout_then_login, redirect_to_login
from transaction.models import (TransactionClaim, TransactionOrder)
from member.models import (Enterprise, Bank, RegisterInvitationCode, MEMBER_ENABLED,
    MEMBER_PENDING, MEMBER_DISABLED, MEMBER_EXPIRED, CODE_ACTIVATED)
from utils.user import get_user_profile
from management.staff_view import BaseStaffView
from utils.constants import TransactionStatus


csrf_protect_m = method_decorator(csrf_protect)


class StaffForm(ModelForm):
    class Meta:
        model = Staff
        fields = '__all__'

        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }


def main_view(request):
    if not request.user.is_authenticated():
        return redirect_to_login('/management/login')

    user_profile = get_user_profile(request.user)
    staff_view = BaseStaffView.get_staff_view(request, user_profile)

    if staff_view:
        return staff_view.create_dashboard()

    return HttpResponse('error: Unknown Staff Type')

templates/management/logged_out.html
{% extends "management/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></div>{% endblock %}

{% block welcome-msg %}{% endblock %}
{% block userlinks %}{% endblock %}
{% block sidebar %}{% endblock %}

{% block content %}



<p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

<p><a href="/management/login">{% trans 'Log in again' %}</a></p>

{% endblock %}

templates/management/market_dashboard.html
{% extends "management/base_site.html" %}
{% load i18n admin_static transaction_tags %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "style/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
欢迎登陆，{{ user_profile.groupname }} {{ user_profile.name }}
</br>
</br>
<div id="content-main">
    <!--div class="app-user module">
    <table id="formset" class="form">
    <caption>历史邀请码记录</caption>
      <thead><tr>
        <th>会员名称</th>
        <th>会员类型</th>
        <th>邀请码</th>
        <th>邀请码状态</th>
        <th>市场经理</th>
        <th>申请时间</th>
      </tr></thead>
    {% if historical_invitations %}
        {% for code in historical_invitations %}
            <tr class="{% cycle row1,row2 %}">
            <td><b><a href="/staff/member/registerinvitationcode/{{ code.id }}/"> {{ code.member_name }}</a></b></td>
            <td>{{ code.get_member_type_display }}</td>
            <td>{{ code.code }}</td>
            <td>{{ code.get_status_display }}</td>
            <td>{{ code.market_manager.name }}</td>
            <td>{{ code.create_date }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td colspan="10" style="text-align: center"><b><a href="/staff/member/registerinvitationcode/">查看全部</a></b></td>
        </tr>
    {% endif %}
    </table>
    </div>
<br/-->
    <div class="app-user module">
    <table id="formset" class="form">
    <caption>等待审核的贴现申请</caption>
      <thead><tr>
        <th>汇票单号</th>
        <th>收款企业</th>
        <th>付款企业</th>
        <th>贴现银行</th>
        <th>承兑银行</th>
        <th>贴现金额</th>
        <th>订单状态</th>
        <th>申请时间</th>
      </tr></thead>
    {% if pending_claim %}
        {% for claim in pending_claim %}
            <tr class="{% cycle row1,row2 %}">
            <td><b><a href="/staff/transaction/transactionclaim/{{ claim.id }}/confirm"> {{ claim.ticket_number  }}</a></b></td>
            <td>{{ claim.receivable_enterprise.name  }}</td>
            <td>{{ claim.pay_enterprise  }}</td>
            <td>{{ claim.ticket_bank  }}</td>
            <td>{{ claim.accept_bank }}</td>
            <td>{{ claim.amount  }}</td>
            <td>{{ claim.get_status_display   }}</td>
            <td>{{ claim.create_time   }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td colspan="10" style="text-align: center"><b><a href="/staff/transaction/transactionclaim/?status__exact=PENDING">查看全部</a></b></td>
        </tr>
    {% endif %}
    </table>
    </div>
<br/>
    <div class="app-user module">
    <table id="formset" class="form">
    <caption>待审核的企业会员</caption>
      <thead><tr>
        <th>企业名称</th>
        <th>省份</th>
        <th>会员星级</th>
        <th>会员状态</th>
        <th>服务市场经理</th>
        <th>注册时间</th>
      </tr></thead>
    {% if enterprise_customers %}
        {% for member in enterprise_customers %}
            <tr class="{% cycle row2,row1 %}">
            <td><b><a href="/staff/member/enterprise/{{ member.id }}/confirm"> {{ member.name }}</a></b></td>
            <td>{{ member.province.name }}</td>
            <td>{{ member.get_level_display }}</td>
            <td>{{ member.get_status_display }}</td>
            <td>{{ member.referee_manager.name }}</td>
            <td>{{ member.create_date }}</td>
            </tr>
        {% endfor %}
        <tr>
        <td colspan="12" style="text-align: center"><b><a href="/staff/member/enterprise/?status__exact=Pending">查看全部</a></b></td>
        </tr>
    {% endif  %}
    </table>
    </div>

    <div class="app-user module">
    <table id="formset" class="form">
    <caption>待审核的银行会员</caption>
      <thead><tr>
        <th>银行全称</th>
        <th>省份</th>
        <th>会员星级</th>
        <th>会员状态</th>
        <th>服务市场经理</th>
        <th>注册时间</th>
      </tr></thead>
    {% if bank_customers %}
        {% for member in bank_customers %}
            <tr class="{% cycle row2,row1 %}">
            <td><b><a href="/staff/member/bank/{{ member.id }}/confirm"> {{ member.name }}</a></b></td>
            <td>{{ member.province.name }}</td>
            <td>{{ member.get_level_display }}</td>
            <td>{{ member.get_status_display }}</td>
            <td>{{ member.referee_manager.name }}</td>
            <td>{{ member.create_date }}</td>
            </tr>
        {% endfor %}
        <tr>
        <td colspan="12" style="text-align: center"><b><a href="/staff/member/bank/?status__exact=Pending">查看全部</a></b></td>
        </tr>
    {% endif  %}
    </table>
    </div>
</div>
{% endblock %}

{% block sidebar %}
<div id="content-related">
    <div class="module" id="recent-actions-module">
        <h2>导航菜单</h2>
        <h3>邀请码</h3>
            <ul class="actionlist">
            <br/>
            <li class="changelink">
                    <a href="/staff/member/registerinvitationcode/">查看历史邀请码</a>
                <br/><br/>
            </li>
            <li class="changelink">
                    <a href="/staff/member/registerinvitationcode/add/">生成新的邀请码</a>
                <br/><br/>
            </li>
            </ul>
        <h3>贴现服务</h3>
            <ul class="actionlist">
            <br/>
            <li class="changelink">
                    <a href="/staff/transaction/transactionorder/?status__exact=PROCESSING">进行中的贴现</a>
                <br/><br/>
            </li>
            <li class="changelink">
                    <a href="/staff/transaction/transactionorder/?status__exact=DONE">已完成的贴现</a>
                <br/><br/>
            </li>
            <li class="changelink">
                    <a href="/staff/transaction/transactionorder/?status__exact=ABORT">过期的贴现服务</a>
                <br/><br/>
            </li>
            </ul>
        <h3>{% trans '企业会员单位' %}</h3>
            <ul class="actionlist">
            <br/>
            <li class="changelink">
                    <a href="/staff/member/enterprise/?status__exact=Pending">待审核的企业会员</a>
                <br/><br/>
            </li>
            <li class="changelink">
                    <a href="/staff/member/enterprise/?status__exact=Enabled">普通企业会员</a>
                <br/><br/>
            </li>
            <li class="changelink">
                    <a href="/staff/member/enterprise/?status__exact=Disabled">禁用企业会员</a>
                <br/><br/>
            </li>
            <li class="changelink">
                    <a href="/staff/member/enterprise/?status__exact=Expired">过期企业会员</a>
                <br/><br/>
            </li>
            </ul>
        <h3>{% trans '银行会员单位' %}</h3>
            <ul class="actionlist">
            <br/>
            <li class="changelink">
                    <a href="/staff/member/bank/?status__exact=Pending">待审核的银行会员</a>
                <br/><br/>
            </li>
            <li class="changelink">
                    <a href="/staff/member/bank/?status__exact=Enabled">普通银行会员</a>
                <br/><br/>
            </li>
            <li class="changelink">
                    <a href="/staff/member/bank/?status__exact=Disabled">禁用银行会员</a>
                <br/><br/>
            </li>
            <li class="changelink">
                    <a href="/staff/member/bank/?status__exact=Expired">过期银行会员</a>
                <br/><br/>
            </li>
            </ul>

        <h3>{% trans '安全设置' %}</h3>
            <ul class="actionlist">
                <br/>
            <li class="changelink">
                    <a href="/staff/management/staff/{{ user_id }}/">查看信息</a>
                <br/><br/>
            </li>
            <li class="changelink">
                    <a href="/management/password_change/">修改密码</a>
                <br/><br/>
            </li>
            </ul>
    </div>
</div>
{% endblock %}

templates/management/notify.html
{% extends "management/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "style/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="/management/main">首页</a>
</div>
{% endblock %}



{% block content %}
<br/>
<div id="content-main">
    {{ info | safe }}
</div>
{% endblock %}

<!-- management/notify.html -->